---
title: "Untitled"
author: "Matt Prest"
date: "December 18, 2018"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


```{r cars}
library(dplyr)
library(ggplot2)
library(tidyr)
library(stringr)
library(lubridate)


income <- read.csv("C:\\Users\\Matt\\Desktop\\Stats Stuff\\county_income.csv", stringsAsFactors = F)
split_names <- (str_split(income$NAME, boundary("word")))
state <- c()
county <- c()

for(i in 1:length(split_names))
{
  test <- unlist(split_names[[i]])
  state_test <- test[[length(test)]]
  
  if(state_test == "Hampshire" || state_test == "Jersy" || state_test == "Mexico" || state_test == "York" || state_test == "Carolina" || state_test == "Dakota" || state_test == "Island" || state_test == "Rico")
  {
    state[[i]] = paste(test[[length(test) - 1]], state_test, sep = " ")
    if(length(test) == 7){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]], sep = " ")
    }else if(length(test) == 6){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], sep = " ")
    }else if(length(test) == 5){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], sep = " ")
    }else{
      county[[i]] <- paste(test[[1]], test[[2]], sep = " ")
    }
  }
  else if(state_test == "Virginia")
  {
    if(test[[length(test) - 1]] == "West")
    {
      state[[i]] = paste(test[[length(test) - 1]], state_test, sep = " ")
      if(length(test) == 7){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]], sep = " ")
      }else if(length(test) == 6){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], sep = " ")
      }else if(length(test) == 5){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], sep = " ")
      }else{
        county[[i]] <- paste(test[[1]], test[[2]], sep = " ")
      }
    }
    else
    {
      state[[i]] = state_test
      if(length(test) == 7){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]],test[[6]], sep = " ")
      }else if(length(test) == 6){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]], sep = " ")
      }else if(length(test) == 5){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], sep = " ")
      }else if(length(test) == 4){
        county[[i]] <- paste(test[[1]], test[[2]],test[[3]], sep = " ")
      }else {
        county[[i]] <- paste(test[[1]], test[[2]], sep = " ")
      }
    }
  }
  else if(state_test == "Columbia")
  {
    state[[i]] = paste(test[[4]], test[[5]], state_test, sep = " ")
    county[[i]] = paste(test[[1]], test[[2]], test[[3]], sep = " ")
  }
  else
  {
    state[[i]] = state_test
    if(length(test) == 7){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]],test[[6]], sep = " ")
    }else if(length(test) == 6){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], test[[5]], sep = " ")
    }else if(length(test) == 5){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], test[[4]], sep = " ")
    }else if(length(test) == 4){
      county[[i]] <- paste(test[[1]], test[[2]],test[[3]], sep = " ")
    }else {
      county[[i]] <- paste(test[[1]], test[[2]], sep = " ")
    }
  }
}

income <- cbind(income, state)
income <- cbind(income, county)
income$GEOID <- factor(income$GEOID)
income <- mutate(income, label = substring(label,52))
for(i in 1:length(income$label))
{
  if(income$label[[i]] == "l")
  {
    income$label[[i]] <- "all categories"
  }else if(income$label[[i]] == "l!!Same house 1 year ago")
  {
    income$label[[i]] <- "no move"
  }else if(income$label[[i]] == "l!!Moved within same county")
  {
    income$label[[i]] <- "change house"
  }else if(income$label[[i]] == "l!!Moved from different county within same state")
  {
    income$label[[i]] <- "change state"
  }else if(income$label[[i]] == "l!!Moved from different state")
  {
    income$label[[i]] <- "change county"
  }
}
income$label <- factor(income$label)
#dataframe with NA values, use with discrestion
income_na <- income
#dataframe with zeros in place of NA values, make the assumption that all NA values were from poor neighborhoods and that this will not effect averages much. great for summations
income_zeros <- mutate_all(income, funs(ifelse(is.na(.), 0, .)))
#dataframe with NA valued rows removed, This one will best handle averages 
income_RR <- income[complete.cases(income), ]


#3a ii, repeated this code for different labels and years
income_RR %>% filter(label == "all categories") %>%
  arrange(desc(median_income_2016))

#4a
final_plot <- income_RR %>% filter(label == "all categories")
final_plot <- final_plot %>% mutate(income_change = median_income_2016 - median_income_2011)

ggplot(final_plot, aes(x = state, y = income_change)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = -90, hjust = 1)) +
  labs(x = "State", y = "Dollars", title = "Difference in median income from 2011 to 2016", 
subtitle = "Same house as 1 year ago")


#5
sim_data <- replicate(10000, {
  X <- rexp(1, 1/2)
  Y <- rexp(1, 1/3)
  Z <- X + Y
})
hist(sim_data, probability = TRUE)




#6
rugby_is_superior <- read.csv("http://stat.slu.edu/~speegled/final_problem_6.csv")
head(rugby_is_superior)
Rugby <- rugby_is_superior %>% filter(sport == "rugby")
Football <- rugby_is_superior %>% filter(sport == "nfl")

#null hypothesis: there is no difference between the mean weight of Rugby Wings and NFL wide recievers
#alternative hypothesis:  the mean weight of Rugby Wings and NFL wide recievers are not equal
t.test(Rugby$weight, Football$weight, alternative = "two")
#the p-value = 0.09832 which is greater than our alpha value therefore we do not reject the null hypothesis
#in terms of our data this means we do not have sufficient evidence to suggest that there is a difference
#in mean body weight between professional rugby Wing players and NFL wide Receivers

#7
#b

#8
#a
problem_8 <- read.csv("http://stat.slu.edu/~speegled/final_problem_8.csv")
head(problem_8)
ggplot(problem_8, aes(x = floor, y = price)) + geom_point()
ggplot(problem_8, aes(x = front, y = price)) + geom_point()
#b
#model of price as a function of floor and front
mod1 <- lm(price ~ ., data = problem_8)
summary(mod1)
#price = 26.560701 + 0.018393*floor + 0.283914*front

plot(mod1)
#there are some large outliers though they are not quite in the high leverage areas, there is no u shape
#in the first plot but the plot of standardized residuals vs theoretical quantities is not flat and straight.
#This indicates that the variance is not constant across the fitted values.

#c
new_house <-  26.560701 + 0.018393*1500 + 0.283914*40
#expected price of this house is 65.5

#d
mod2 <- lm(price ~ floor, data = problem_8)
summary(mod2)
#price = 33.916831 + 0.020213*floor
new_house_2 <- 33.916831 + 0.020213*1500
#price of 1500 square foot hous is 64.2

#e
predict(mod2, newdata = data.frame(floor = 1500), interval = "prediction", level = 0.9)
#the 90% confidence prediction interval of a new house with 1500 sqft is from 48.9 to 79.6,
#our family has a budget of 55 which falls within this range therefore there is a better than
#10% chance that the next house will affordable for them





```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
final_plot <- income_RR %>% filter(label == "all categories")
final_plot <- final_plot %>% mutate(income_change = median_income_2016 - median_income_2011)

ggplot(final_plot, aes(x = state, y = income_change)) + geom_boxplot() + 
  theme(axis.text.x = element_text(angle = -90, hjust = 1)) +
  labs(x = "State", y = "Dollars", title = "Difference in median income from 2011 to 2016", 
subtitle = "Same house as 1 year ago")

sim_data <- replicate(10000, {
  X <- rexp(1, 1/2)
  Y <- rexp(1, 1/3)
  Z <- X + Y
})
hist(sim_data, probability = TRUE)

problem_8 <- read.csv("http://stat.slu.edu/~speegled/final_problem_8.csv")
head(problem_8)
ggplot(problem_8, aes(x = floor, y = price)) + geom_point()
ggplot(problem_8, aes(x = front, y = price)) + geom_point()

mod1 <- lm(price ~ ., data = problem_8)
summary(mod1)
#price = 26.560701 + 0.018393*floor + 0.283914*front

plot(mod1)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
